
ROBOT_AVERAGE_SPEED = 0.3  # m/s
AVERAGE_WAITING_TIME = 3 # s
ROBOT_QUALITY_S = 100 # s

POSESTAMPED_FRAME_ID = 'map' 

VALIDATION_TIMEOUT = 30.0  # s
REQUEST_PATH_COMPUTING_TIMEOUT = 0.1 # s
COMPUTE_PLAN_TIMEOUT = 0.5 # s
CLEAR_FINISHED_PERIOD = 5  # s

ALLOCATION_INTERVAL = 1 # s
MISSION_PUBLICATION_INTERVAL = 0.2 # s


FLEET_STATE_TOPIC = '/fleet/fleet_state'
MISSION_REQUEST_TOPIC = '/mission/mission_request'
VALIDATION_TOPIC = '/mission/validation'
MISSIONS_STATE_TOPIC = '/mission/missions_state'